db:
  mongodb:
    host: mongodb # mongodb container name or mongodb host address
    port: 27017
    replica_set: rs0
    dbname: db_name # mongodb database name
    collection: collection_name # mongodb collection name
    user: root
    password: root

grpc:
  listen_addr: 0.0.0.0:8080 # grpc listen address
  max_msg_size: 1024 # grpc max message size
  timeout: 10s

log:
  format: text
  level: debug
  file: ""