// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutableEthereumBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        []byte                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Data          []*TransactionSigned   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutableEthereumBatch) Reset() {
	*x = ExecutableEthereumBatch{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutableEthereumBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutableEthereumBatch) ProtoMessage() {}

func (x *ExecutableEthereumBatch) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutableEthereumBatch.ProtoReflect.Descriptor instead.
func (*ExecutableEthereumBatch) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutableEthereumBatch) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *ExecutableEthereumBatch) GetData() []*TransactionSigned {
	if x != nil {
		return x.Data
	}
	return nil
}

// 여러 배치를 한 번에 보낼 용도의 래퍼 (예시의 data: [ ... ] 구조)
type ExecutableConsensusOutput struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Data          []*ExecutableEthereumBatch `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutableConsensusOutput) Reset() {
	*x = ExecutableConsensusOutput{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutableConsensusOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutableConsensusOutput) ProtoMessage() {}

func (x *ExecutableConsensusOutput) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutableConsensusOutput.ProtoReflect.Descriptor instead.
func (*ExecutableConsensusOutput) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutableConsensusOutput) GetData() []*ExecutableEthereumBatch {
	if x != nil {
		return x.Data
	}
	return nil
}

type Signature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	R             []byte                 `protobuf:"bytes,1,opt,name=r,proto3" json:"r,omitempty"`
	S             []byte                 `protobuf:"bytes,2,opt,name=s,proto3" json:"s,omitempty"`
	OddYParity    bool                   `protobuf:"varint,3,opt,name=odd_y_parity,json=oddYParity,proto3" json:"odd_y_parity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signature) Reset() {
	*x = Signature{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signature) ProtoMessage() {}

func (x *Signature) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signature.ProtoReflect.Descriptor instead.
func (*Signature) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *Signature) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *Signature) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *Signature) GetOddYParity() bool {
	if x != nil {
		return x.OddYParity
	}
	return false
}

type TransactionSigned struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Hash      []byte                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Signature *Signature             `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Types that are valid to be assigned to Tx:
	//
	//	*TransactionSigned_Legacy
	Tx            isTransactionSigned_Tx `protobuf_oneof:"tx"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionSigned) Reset() {
	*x = TransactionSigned{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionSigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionSigned) ProtoMessage() {}

func (x *TransactionSigned) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionSigned.ProtoReflect.Descriptor instead.
func (*TransactionSigned) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionSigned) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *TransactionSigned) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *TransactionSigned) GetTx() isTransactionSigned_Tx {
	if x != nil {
		return x.Tx
	}
	return nil
}

func (x *TransactionSigned) GetLegacy() *TxLegacy {
	if x != nil {
		if x, ok := x.Tx.(*TransactionSigned_Legacy); ok {
			return x.Legacy
		}
	}
	return nil
}

type isTransactionSigned_Tx interface {
	isTransactionSigned_Tx()
}

type TransactionSigned_Legacy struct {
	Legacy *TxLegacy `protobuf:"bytes,10,opt,name=legacy,proto3,oneof"`
}

func (*TransactionSigned_Legacy) isTransactionSigned_Tx() {}

type To struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*To_Call
	//	*To_Create
	Kind          isTo_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *To) Reset() {
	*x = To{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *To) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*To) ProtoMessage() {}

func (x *To) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use To.ProtoReflect.Descriptor instead.
func (*To) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *To) GetKind() isTo_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *To) GetCall() []byte {
	if x != nil {
		if x, ok := x.Kind.(*To_Call); ok {
			return x.Call
		}
	}
	return nil
}

func (x *To) GetCreate() bool {
	if x != nil {
		if x, ok := x.Kind.(*To_Create); ok {
			return x.Create
		}
	}
	return false
}

type isTo_Kind interface {
	isTo_Kind()
}

type To_Call struct {
	Call []byte `protobuf:"bytes,1,opt,name=call,proto3,oneof"`
}

type To_Create struct {
	Create bool `protobuf:"varint,2,opt,name=create,proto3,oneof"`
}

func (*To_Call) isTo_Kind() {}

func (*To_Create) isTo_Kind() {}

type TxLegacy struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ChainId       *wrapperspb.UInt64Value `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Nonce         uint64                  `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	GasPrice      []byte                  `protobuf:"bytes,3,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	GasLimit      uint64                  `protobuf:"varint,4,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	To            *To                     `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	Value         []byte                  `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	Input         []byte                  `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxLegacy) Reset() {
	*x = TxLegacy{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxLegacy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxLegacy) ProtoMessage() {}

func (x *TxLegacy) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxLegacy.ProtoReflect.Descriptor instead.
func (*TxLegacy) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *TxLegacy) GetChainId() *wrapperspb.UInt64Value {
	if x != nil {
		return x.ChainId
	}
	return nil
}

func (x *TxLegacy) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *TxLegacy) GetGasPrice() []byte {
	if x != nil {
		return x.GasPrice
	}
	return nil
}

func (x *TxLegacy) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *TxLegacy) GetTo() *To {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *TxLegacy) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TxLegacy) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\n" +
	"storagemgr\x1a\x1egoogle/protobuf/wrappers.proto\"d\n" +
	"\x17ExecutableEthereumBatch\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\x121\n" +
	"\x04data\x18\x02 \x03(\v2\x1d.storagemgr.TransactionSignedR\x04data\"T\n" +
	"\x19ExecutableConsensusOutput\x127\n" +
	"\x04data\x18\x01 \x03(\v2#.storagemgr.ExecutableEthereumBatchR\x04data\"I\n" +
	"\tSignature\x12\f\n" +
	"\x01r\x18\x01 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x02 \x01(\fR\x01s\x12 \n" +
	"\fodd_y_parity\x18\x03 \x01(\bR\n" +
	"oddYParity\"\x92\x01\n" +
	"\x11TransactionSigned\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\fR\x04hash\x123\n" +
	"\tsignature\x18\x02 \x01(\v2\x15.storagemgr.SignatureR\tsignature\x12.\n" +
	"\x06legacy\x18\n" +
	" \x01(\v2\x14.storagemgr.TxLegacyH\x00R\x06legacyB\x04\n" +
	"\x02tx\"<\n" +
	"\x02To\x12\x14\n" +
	"\x04call\x18\x01 \x01(\fH\x00R\x04call\x12\x18\n" +
	"\x06create\x18\x02 \x01(\bH\x00R\x06createB\x06\n" +
	"\x04kind\"\xdf\x01\n" +
	"\bTxLegacy\x127\n" +
	"\bchain_id\x18\x01 \x01(\v2\x1c.google.protobuf.UInt64ValueR\achainId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\x04R\x05nonce\x12\x1b\n" +
	"\tgas_price\x18\x03 \x01(\fR\bgasPrice\x12\x1b\n" +
	"\tgas_limit\x18\x04 \x01(\x04R\bgasLimit\x12\x1e\n" +
	"\x02to\x18\x05 \x01(\v2\x0e.storagemgr.ToR\x02to\x12\x14\n" +
	"\x05value\x18\x06 \x01(\fR\x05value\x12\x14\n" +
	"\x05input\x18\a \x01(\fR\x05inputB=Z;github.com/off-chain-storage/offchain-storage-manager/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_common_proto_goTypes = []any{
	(*ExecutableEthereumBatch)(nil),   // 0: storagemgr.ExecutableEthereumBatch
	(*ExecutableConsensusOutput)(nil), // 1: storagemgr.ExecutableConsensusOutput
	(*Signature)(nil),                 // 2: storagemgr.Signature
	(*TransactionSigned)(nil),         // 3: storagemgr.TransactionSigned
	(*To)(nil),                        // 4: storagemgr.To
	(*TxLegacy)(nil),                  // 5: storagemgr.TxLegacy
	(*wrapperspb.UInt64Value)(nil),    // 6: google.protobuf.UInt64Value
}
var file_common_proto_depIdxs = []int32{
	3, // 0: storagemgr.ExecutableEthereumBatch.data:type_name -> storagemgr.TransactionSigned
	0, // 1: storagemgr.ExecutableConsensusOutput.data:type_name -> storagemgr.ExecutableEthereumBatch
	2, // 2: storagemgr.TransactionSigned.signature:type_name -> storagemgr.Signature
	5, // 3: storagemgr.TransactionSigned.legacy:type_name -> storagemgr.TxLegacy
	6, // 4: storagemgr.TxLegacy.chain_id:type_name -> google.protobuf.UInt64Value
	4, // 5: storagemgr.TxLegacy.to:type_name -> storagemgr.To
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[3].OneofWrappers = []any{
		(*TransactionSigned_Legacy)(nil),
	}
	file_common_proto_msgTypes[4].OneofWrappers = []any{
		(*To_Call)(nil),
		(*To_Create)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
