// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: storage_manager.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_storage_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_storage_manager_proto_rawDescGZIP(), []int{0}
}

func (x *StoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StoreResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_storage_manager_proto protoreflect.FileDescriptor

const file_storage_manager_proto_rawDesc = "" +
	"\n" +
	"\x15storage_manager.proto\x12\n" +
	"storagemgr\x1a\fcommon.proto\"C\n" +
	"\rStoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2a\n" +
	"\x0eStorageManager\x12O\n" +
	"\vStoreBlocks\x12%.storagemgr.ExecutableConsensusOutput\x1a\x19.storagemgr.StoreResponseB=Z;github.com/off-chain-storage/offchain-storage-manager/protob\x06proto3"

var (
	file_storage_manager_proto_rawDescOnce sync.Once
	file_storage_manager_proto_rawDescData []byte
)

func file_storage_manager_proto_rawDescGZIP() []byte {
	file_storage_manager_proto_rawDescOnce.Do(func() {
		file_storage_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_manager_proto_rawDesc), len(file_storage_manager_proto_rawDesc)))
	})
	return file_storage_manager_proto_rawDescData
}

var file_storage_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_storage_manager_proto_goTypes = []any{
	(*StoreResponse)(nil),             // 0: storagemgr.StoreResponse
	(*ExecutableConsensusOutput)(nil), // 1: storagemgr.ExecutableConsensusOutput
}
var file_storage_manager_proto_depIdxs = []int32{
	1, // 0: storagemgr.StorageManager.StoreBlocks:input_type -> storagemgr.ExecutableConsensusOutput
	0, // 1: storagemgr.StorageManager.StoreBlocks:output_type -> storagemgr.StoreResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storage_manager_proto_init() }
func file_storage_manager_proto_init() {
	if File_storage_manager_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_manager_proto_rawDesc), len(file_storage_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_manager_proto_goTypes,
		DependencyIndexes: file_storage_manager_proto_depIdxs,
		MessageInfos:      file_storage_manager_proto_msgTypes,
	}.Build()
	File_storage_manager_proto = out.File
	file_storage_manager_proto_goTypes = nil
	file_storage_manager_proto_depIdxs = nil
}
